### ISSUE TITLE
Adding "deauth all networks" feature

### ISSUE THREAD

**Issue by YoavLevi** [tesa-klebeband/RTL8720dn-Deauther#12]
Hello and thank you Tesa for this project.
I've been playing with it trying to make it deauth all networks around however for some reason it does not deauth all the devices at each network as it's done via the single deauth button of the HTML server.
I was trying to do something like this in the loop function (I omitted most of it except for this part) :
![image](https://github.com/user-attachments/assets/ee864ec3-660d-47a9-9c63-48f65effde27)
However, I'm not sure why it's not working well.
Do you have any idea how to implement this feature more successfully?

**Comment by tesa-klebeband** [comment]
Hi,
I believe it doesn't work because sending a single frame (a single call to the tx function) might not be enough. I have mentioned in another issue, that reopening the WiFi, as startDeauth does it, is really slow. You can use wext_set_channel to set the WiFi channel before transmitting a few frames, then repeat it with another networks channel...

**Comment by YoavLevi** [comment]
Thank you for replying to me. I want to try what you've suggested however I couldn't find out what is the interface name of the WiFi in the BW16 board, as needed by the declaration of the function you've mentioned:

int wext_set_channel(const char *ifname, __u8 ch);

Do you know what value should be substituted to the  *ifname variable?

**Comment by tesa-klebeband** [comment]
The name for the WiFi interface should be WLAN0_NAME

**Comment by YoavLevi** [comment]
Thanks, it worked!
After only changing the channel for each network the deauth packets are sent more rapidly and successfully act on all networks.
